### ISSUE TITLE
please check , my def is correct ?

### ISSUE THREAD

**Issue by bugbounted** [Enrialonso/playwright-on-docker-python#1]
def get_last_video_url(username):
    with sync_playwright() as p:
        #for navigator in [p.chromium, p.firefox]:
            print("get_last_video_url def started")
            browser = p.chromium.launch(headless=False)
            page = browser.new_page()
            page.goto("https://fing.fingil.workers.dev/@{}".format(username))
            latest_video = page.query_selector('xpath=/html/body/section[2]/div[1]/article[1]/div/div[3]/div[1]/a[2]')
        url = latest_video.get_property('href')
        browser.close()
		print(url.text)
        return url

**Comment by enrialonso** [comment]
```python
def get_last_video_url(username):
    with sync_playwright() as p:
    #for navigator in [p.chromium, p.firefox]:
    print("get_last_video_url def started")
    browser = p.chromium.launch(headless=False)
    page = browser.new_page()
    page.goto("https://fing.fingil.workers.dev/@{}".format(username))
    latest_video = page.query_selector('xpath=/html/body/section[2]/div[1]/article[1]/div/div[3]/div[1]/a[2]')
    url = latest_video.get_property('href')
    browser.close()
    print(url.text)
    return url
```
@elmirarokni 
I think was correct, if on your text editor looks like the example of code above, u can improve the selector for the `latest_video` variable, try to get the class tag or id of the html element, can u share the error output?
